Refactoring
ArtemKlots/travel_bill pull request #1
Opened 2018-12-18 20:24 UTC by ArtemKlots

2018-12-21 17:44 UTC, EduardRakov requested changes

2018-12-21 17:44 UTC, EduardRakov commented on src/main/java/com/travelBill/telegram/TelegramBot.java
>              execute(message);
Look at https://github.com/rainerhahnekamp/sneakythrow

2018-12-21 17:44 UTC, EduardRakov commented on src/main/java/com/travelBill/telegram/TelegramBot.java
>              execute(message);
- Use methods from Update e.g. hasMessage() etc.
- Throw and handle the case when no message or...

2018-12-21 17:44 UTC, EduardRakov commented on src/main/java/com/travelBill/telegram/TelegramBot.java
>              execute(message);
```
private User setupUser(Update update) {
        org.telegram.telegrambots.meta.api.objects.User u;
        if (update.hasMessage()) {
            u = update.getMessage().getFrom();

        } else if (update.hasCallbackQuery()) {
            u = update.getCallbackQuery().getFrom();
        }

        return telegramUserService.setupUser(u);
    }
```

2018-12-21 17:44 UTC, EduardRakov commented on src/main/java/com/travelBill/telegram/scenario/ScenarioFactory.java
> +        if (type == null) {
use isNull() instead

2018-12-21 17:44 UTC, EduardRakov commented on src/main/java/com/travelBill/telegram/scenario/event/EventScenarioFactory.java
> +        if (type == null) {
DRY

2018-12-24 20:05 UTC, ArtemKlots commented
@EduardRakov ready for review

2019-01-04 17:01 UTC, EduardRakov approved these changes

2019-01-04 17:01 UTC, merged